### ISSUE TITLE
cannot install latest version with zef

### ISSUE THREAD

**Issue by grizzlysmit** [Demayl/raku-Email-Valid#10]
Hi this is currently broken looks like you forgot to update `META6.json` ??? or something

```sh
$ zef install Email::Valid
===> Searching for: Email::Valid
===> Updating fez mirror: https://360.zef.pm/
===> Updated fez mirror: https://360.zef.pm/
===> Updating rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
===> Updated rea mirror: https://raw.githubusercontent.com/Raku/REA/main/META.json
===> Searching for missing dependencies: Net::DNS
===> Extraction: Failed to find a META6.json file for Email::Valid:ver<1.0.4>:auth<github:Demayl> -- failure is likely
[Email::Valid] Extracting with plugin Zef::Service::Shell::tar+{<anon|1>} aborted.
Type check failed for return value; expected IO::Path but got Any (Any)
```

**Comment by Demayl** [comment]
Looks like that zef can't get the latest release ( which is 1.0.5 ).
As a temporary workaround you can use 
`zef install https://github.com/Demayl/raku-Email-Valid.git`
```
===> Testing: Email::Valid:ver<1.0.5>:auth<github:demayl>
===> Testing [OK] for Email::Valid:ver<1.0.5>:auth<github:demayl>
===> Installing: Email::Valid:ver<1.0.5>:auth<github:demayl>
```
I will take a closer look in the following days what changed in zef to cause this issue

**Comment by grizzlysmit** [comment]
On 9/12/22 10:06, Denis Kanchev wrote:
> |zef install https://github.com/Demayl/raku-Email-Valid.git|
|That worked, thanks|
-- 

    .~.     There are many things that I love....
    /V\         but God Comes way above all else❣❣❣❣
   /( )\    Francis (Grizzly) Smit
   ^^-^^http://www.smit.id.au/

**Comment by sdondley** [comment]
I'm not sure exactly what the problem is but the tarball for 1.0.5 version is showing up as 0 bytes on github: https://github.com/Raku/REA/blob/main/archive/E/Email::Valid/Email::Valid:ver%3C1.0.5%3E:auth%3Cgithub:Demayl%3E.tar.gz

So it never got uploaded.

Compare this to version 1.0.4 which shows as 10.1 kb: https://github.com/Raku/REA/blob/main/archive/E/Email::Valid/Email::Valid:ver%3C1.0.4%3E:auth%3Cgithub:demayl%3E.tar.gz

**Comment by Demayl** [comment]
After a version bump it looks like it's working
