### ISSUE TITLE
Warning always printed

### ISSUE THREAD

**Issue by andinus** [Demayl/raku-Email-Valid#11]
https://github.com/Demayl/raku-Email-Valid/blob/b47d679695014d2e5e2aab64e5a46281717136ed/lib/Email/Valid.rakumod#L111

This warning is always printed, even if the lookup was successful. Looks like it wasn't intended to be used like so:

![Screenshot 2023-12-06 at 8 18 12 PM](https://github.com/Demayl/raku-Email-Valid/assets/62012039/8f7cbbc0-c43b-4f3a-b9e1-9f3e761a262b)

**Comment by andinus** [comment]
Related:
- https://stackoverflow.com/a/64277079 highlights this usage
- https://stackoverflow.com/a/60695257

**Comment by Demayl** [comment]
Thanks for the detailed info!
Indeed this wasn't intended. I hoped that the author of Net::DNS will add a timeout in the meantime and this was supposed to be a "temporary" hack :D
